#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    c=n-1
    for j in range(0,n):
        for i in range(0,n):
            if i>=c:
                print("#",end="")
            else:
                print(" ",end="")
        c-=1
        print("")
        

if __name__ == '__main__':
    n = int(input())

    staircase(n)
